spring:
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    hikari:
      connection-init-sql: select 1
      connection-timeout: 6000
      driver-class-name: com.p6spy.engine.spy.P6SpyDriver
      idle-timeout: 6000
      initialization-fail-timeout: 1
      jdbc-url: jdbc:p6spy:mysql://127.0.0.1:3306/mwork?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
      password: root
      username: root
      validation-timeout: 6000
      maximum-pool-size: 10
      minimum-idle: 2
      pool-name: mwork-datasource-hikari-poll
mwork:
  authConfig:
    enabled: false
  validation:
    showMessageEnabled: true
